
package org.aavso.tools.vstar.input.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AAVSOObsWebService", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AAVSOObsWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.aavso.tools.vstar.input.ws.client.StarInfo
     * @throws ConnectionException_Exception
     * @throws UnknownStarError_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStarInfoByName", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetStarInfoByName")
    @ResponseWrapper(localName = "getStarInfoByNameResponse", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetStarInfoByNameResponse")
    public StarInfo getStarInfoByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConnectionException_Exception, UnknownStarError_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.aavso.tools.vstar.input.ws.client.StarInfo
     * @throws ConnectionException_Exception
     * @throws UnknownAUIDError_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStarInfoByAUID", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetStarInfoByAUID")
    @ResponseWrapper(localName = "getStarInfoByAUIDResponse", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetStarInfoByAUIDResponse")
    public StarInfo getStarInfoByAUID(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConnectionException_Exception, UnknownAUIDError_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<org.aavso.tools.vstar.input.ws.client.Ob>
     * @throws ConnectionException_Exception
     * @throws ObservationReadError_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getObservationsInRange", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetObservationsInRange")
    @ResponseWrapper(localName = "getObservationsInRangeResponse", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetObservationsInRangeResponse")
    public List<Ob> getObservationsInRange(
        @WebParam(name = "arg0", targetNamespace = "")
        StarInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws ConnectionException_Exception, ObservationReadError_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<org.aavso.tools.vstar.input.ws.client.ValidObservation>
     * @throws ConnectionException_Exception
     * @throws ObservationReadError_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getObservationsWithJDRange", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetObservationsWithJDRange")
    @ResponseWrapper(localName = "getObservationsWithJDRangeResponse", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetObservationsWithJDRangeResponse")
    public List<ValidObservation> getObservationsWithJDRange(
        @WebParam(name = "arg0", targetNamespace = "")
        StarInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws ConnectionException_Exception, ObservationReadError_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<org.aavso.tools.vstar.input.ws.client.ValidObservation>
     * @throws ConnectionException_Exception
     * @throws ObservationReadError_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllObservations", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetAllObservations")
    @ResponseWrapper(localName = "getAllObservationsResponse", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", className = "org.aavso.tools.vstar.input.ws.client.GetAllObservationsResponse")
    public List<ValidObservation> getAllObservations(
        @WebParam(name = "arg0", targetNamespace = "")
        StarInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ConnectionException_Exception, ObservationReadError_Exception
    ;

}
