
package org.aavso.tools.vstar.input.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AAVSOObsWebServiceService", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/", wsdlLocation = "http://localhost:8080/obs?wsdl")
public class AAVSOObsWebServiceService
    extends Service
{

    private final static URL AAVSOOBSWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.aavso.tools.vstar.input.ws.client.AAVSOObsWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.aavso.tools.vstar.input.ws.client.AAVSOObsWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/obs?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/obs?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AAVSOOBSWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public AAVSOObsWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AAVSOObsWebServiceService() {
        super(AAVSOOBSWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://endpoint.ws.input.vstar.tools.aavso.org/", "AAVSOObsWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns AAVSOObsWebService
     */
    @WebEndpoint(name = "AAVSOObsWebServicePort")
    public AAVSOObsWebService getAAVSOObsWebServicePort() {
        return super.getPort(new QName("http://endpoint.ws.input.vstar.tools.aavso.org/", "AAVSOObsWebServicePort"), AAVSOObsWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AAVSOObsWebService
     */
    @WebEndpoint(name = "AAVSOObsWebServicePort")
    public AAVSOObsWebService getAAVSOObsWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.ws.input.vstar.tools.aavso.org/", "AAVSOObsWebServicePort"), AAVSOObsWebService.class, features);
    }

}
