
package org.aavso.tools.vstar.input.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "UnknownStarError", targetNamespace = "http://endpoint.ws.input.vstar.tools.aavso.org/")
public class UnknownStarError_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownStarError faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnknownStarError_Exception(String message, UnknownStarError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnknownStarError_Exception(String message, UnknownStarError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.aavso.tools.vstar.input.ws.client.UnknownStarError
     */
    public UnknownStarError getFaultInfo() {
        return faultInfo;
    }

}
