
package org.aavso.tools.vstar.input.ws.endpoint.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1.6
 * 
 */
@XmlRootElement(name = "UnknownAUIDError", namespace = "http://endpoint.ws.input.vstar.tools.aavso.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnknownAUIDError", namespace = "http://endpoint.ws.input.vstar.tools.aavso.org/")
public class UnknownAUIDErrorBean {

    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
