# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches:
        - "**"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up environment
      run:
        echo "DISPLAY=localhost:1.0" >> $GITHUB_ENV
    - name: Build with Ant
      run:
        ant -Djava.awt.headless=false -noinput -buildfile build.xml test
