# This workflow will build a Java project with Ant and run VStar's unit tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: VStar Unit Tests

on:
  push:
    branches:
        - "**"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11' , '14', '15', '16' ]

    name: Java ${{ matrix.Java }} VStar UTs

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Create plugin dir
      run:
        mkdir -p ~/vstar_plugins
    - name: Create plugin libs dir
      run:
        mkdir -p ~/vstar_plugin_libs
    - name: Build with Ant
      run:
        ant -noinput -buildfile build.xml test
